pivvit_api:
    resource: "@PivvitApiBundle/Resources/config/routing.yml"
    prefix:   /

pivvit_front:
    resource: "@PivvitFrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
