<?php

namespace Pivvit\ApiBundle\Repository;

/**
 * OfferingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferingRepository extends \Doctrine\ORM\EntityRepository
{
}
